- lib/rexml/parsers/baseparser.rb
Hi, I've been fuzzing rexml (with [kisaten](https://github.com/zelivans/kisaten)) and found multiple bugs, I will attempt to fix what I can and send PRs, or open issues for the rest. This bug is the first.
When rexml finds an incomplete processing instruction node, it fails with a `NoMethodError` that is caught by a `REXML::ParseException`, due to the `match` function returning nil. This proposed fix raises an informative exception message when the match fails.
```
/home/ariel/afl-kisaten/private/sandbox/rexml/rexml/lib/rexml/parsers/treeparser.rb:96:in `rescue in parse': #<NoMethodError: undefined method `[]' for nil:NilClass> (REXML::ParseException)
```
Try parsing with `REXML::Document.new` any of the following: `<?>`, `<? bla >`
> Raise appropriate exception when failing to match instruction node

- lib/rexml/parsers/baseparser.rb
In `BaseParser#pull_event`, when the ending tag can't be matched, `md` resolves to nil. The subsequent check of the value of `md[1]` will fail with `NoMethodError` (caught with `REXML::ParseException`). This proposed fix prevents the nil call and raises a `REXML::ParseException` directly.
```
/home/ariel/afl-kisaten/private/sandbox/rexml/rexml/lib/rexml/parsers/baseparser.rb:442:in `rescue in pull_event': #<NoMethodError: undefined method `[]' for nil:NilClass> (REXML::ParseException)
```
With `REXML::Document.new` try:
```
<b></
```
> Raise appropriate exception when failing to match end tag

- lib/rexml/formatters/default.rb
In `REXML::Formatters::Default#write_instruction` a `TypeError` exception is raised when `node.content` is nil. I am not sure if it is ever supposed to become nil, but my fuzzer did catch cases where a `TypeError` was raised in these lines. I am proposing this naive fix, close if you prefer to write a better fix that prevents this issue or raises an appropriate exception.
```
/home/ariel/afl-kisaten/private/sandbox/rexml/rexml/lib/rexml/formatters/default.rb:107:in `write_instruction': no implicit conversion of nil into String (TypeError)
from /home/ariel/afl-kisaten/private/sandbox/rexml/rexml/lib/rexml/formatters/default.rb:39:in `write'
from /home/ariel/afl-kisaten/private/sandbox/rexml/rexml/lib/rexml/formatters/default.rb:80:in `block in write_element'
from …
```
> Prevent TypeError and ArgumentError crash (nil to string conversion) in default formatter

- lib/rexml/parsers/baseparser.rb
Ref: https://github.com/ruby/ruby/pull/1994
`Exception` is rescuing many things it shouldn't rescue like `SignalException` for instance.
> Rescue StandardError rather than Exception

- lib/rexml/text.rb
When input texts include non-printable characters, e.g. "\b" (`^H`),  REXML gives up parsing it, printing the non-printable characters as is. This will confuse users because the error messages in a terminal may be broken.
This PR fixes the problem by using `#inspect` to pretty-print those non-printable characters.
> use #inspect to pretty-print meta-characters in error messages

- lib/rexml/functions.rb
- test/rexml/test_functions.rb
Prior to d91e124ab9843d2eaf62071bf029301254c36e2b, an XPath variable could be set to `nil`, in which case it would be silently converted to an empty string. This is clearly still the intended behaviour of this method, as can be seen from the (redundant) `when nil` further down. But, with the introduction of context support, this case was broken, because trying to do `@@context[:node]` would raise a `NoMethodError` if there was no context.
I also noticed that then `when nil` case was redundant, since without it it'll use `nil.to_s`, which is already the empty string, so I removed that in a seperate commit.
> Fix crash with nil XPath variables

- lib/rexml/parsers/baseparser.rb
- test/rexml/parse/test_element.rb
Message less confusing error to human
* Problem: Following error message is not helpful, because you have to reason
that '' actually means it's in the top-level, and the 'div' (not '</div>') is
an end tag
require "rexml/parsers/lightparser"
REXML::Parsers::LightParser.new('</div>').parse
#=> Missing end tag for '' (got 'div')
* Solution: add a special case in error handling just to change the error message
require "rexml/parsers/lightparser"
REXML::Parsers::LightParser.new('</div>').parse
#=> Unexpected top-level end tag (got 'div')
> Message less confusing error to human

- lib/rexml/xmldecl.rb
- test/rexml/test_xml_declaration.rb
`XMLDecl#clone` does not copy its `@writethis` attribute.
This causes that a deeply cloned XML document always outputs XML declaration
that is assumed by the library when the original XML doesn't have it.
```ruby
doc = REXML::Document.new "<root/>"
puts doc.to_s            # => "<root/>"
puts doc.deep_clone.to_s # => "<?xml version='1.0'?><root/>"
```
This fixes the behavior.
```ruby
doc = REXML::Document.new "<root/>"
puts doc.to_s            # => "<root/>"
puts doc.deep_clone.to_s # => "<root/>"
```
> Feature/XMLDecl#clone to copy @writethis attribute

- lib/rexml/source.rb
Ruby 2.7 deprecates taint and it no longer has an effect.
> Only taint on Ruby <2.7

- lib/rexml.rb
- rexml.gemspec
It would be convenient if users can use `REXML::Document` without explicitly `require "rexml/document"`.
https://guides.rubygems.org/name-your-gem/
I heard the following Gemfile setting in a real world application development:
```ruby
gem "rexml", require: "rexml/document"
```
So, I think this could be unnecessary if "rexml/document" will be required by default as a endpoint.
> `require "rexml/document"` by default

- lib/rexml/xpath_parser.rb
While investigating my app, I found an unfamiliar `dclone` method on `Object`, which turned out to be defined here in `xpath_parser.rb` only for using in `xpath_parser.rb`.
I believe this is the very use case of Ruby's most underevaluated feature, Refinements.
With this patch, we're no longer seeing the `dclone` method leaking into our apps.
> Refine dclone definitions not to leak outside of REXML

- rexml.gemspec
These files are meaningless outside the working directory.
> Exclude useless files after installation

- lib/rexml/document.rb
Revises prefatory material, and methods:
- new
- node_type
- clone
- expanded_name
- add
Note well:  When I run this through rdoc, the call-seq for method expanded_name, and its aliased method name, does not show up.  I have no theory that explains that.
> Enhanced RDoc for Document

- lib/rexml/element.rb
- test/test_elements.rb
This is mainly to establish the concept of _base_ _element_, and to be able to retrieve the element elsewhere in the example code.
Next, I'll modify one or two remarks in the existing doc for Elements, then proceed with more RDoc for the class.
> Adding method Elements#parent

- lib/rexml/element.rb
Marking this as a draft b/c it has a couple of TODOs that need review and resolution.
Revised methods:
- []
- attribute
- has_attributes?
- add_attribute
- add_attributes
- delete_attribute
- cdatas
- comments
- instructions
- texts
> Enhanced RDoc for Element

- README.md
- doc/rexml/tasks/tocs/master_toc.rdoc
- lib/rexml/document.rb
- lib/rexml/element.rb
- lib/rexml/light/node.rb
- lib/rexml/rexml.rb
- tasks/tocs.rake
Removes outdated info, adds high-level RDoc.
> Clean up and enhance high-level RDoc

- .github/workflows/test.yml
`actions/setup-ruby` is deprecated now. I replaced it to `ruby/setup-ruby`.
> Use ruby/setup-ruby

- rexml.gemspec
This gem is no longer tested with Rubies older than 2.5, and it's actually broken on at least <= 2.2.
By setting the minimum version in the `gemspec`, we ensure that older Ruby versions don't try to use an incompatible `rexml` version.
_Outdated original description:_
> ~~Ruby 2.3 is the oldest Ruby that still passes all tests when running `rake test`. By setting it in the ~`gemfile`~ gemspec (edit), we ensure that older Ruby versions don't try to use an incompatible `rexml` version.~~
>~~(Note: It's probably trivial to support the older Rubies, but I'll leave that for someone who is interested enough in doing the extra work)~~
> ~~I've taken the liberty of also updating the `NEWS.md`, so that this is ready to release. See #69 for details :)~~
> Add 2.5 as minimum required ruby version for gem

- README.md
> Document that REXML follows the Ruby maintenance cycle

- doc/rexml/tutorial.rdoc
- lib/rexml/rexml.rb
Link from main page to the tutorial.
Also, remove some stray text from example outputs.
> doc: linkt to tutorial

- rexml.gemspec
This gem exposes no executables.
> gemspec: Drop unused directives

- lib/rexml/element.rb
* Add missing plus for `Element#has_text?`.
* Remove unneeded hash and duplicated `the` for `Element#text`.
> Fix RDoc for Element

- .github/workflows/test.yml
Here's a patch that adds CI configurations for Rubies 3.0, 3.1, and 3.2 that are currently untested.
> CI against Ruby 3.0, 3.1, and 3.2

- lib/rexml/attribute.rb
- lib/rexml/entity.rb
- lib/rexml/formatters/pretty.rb
- lib/rexml/namespace.rb
- lib/rexml/text.rb
- test/test_core.rb
- test/test_document.rb
Originally, the inefficiency was discovered when working through the bug report in the `rubocop` repository - https://github.com/rubocop/rubocop/issues/11657.
Tested on the `rubocop` repository. `git clone` it, point `rexml` to the local repository, `bundle install` etc and run inside it:
```
bundle exec rubocop --profile --memory --format junit --out results/rubocop.xml lib/rubocop/cop/layout
```
```
Total allocated: 630.15 MB (8838482 objects)
Total retained:  53.50 MB (445069 objects)
allocated memory by gem
-----------------------------------
294.26 MB  rexml/lib
214.78 MB  rubocop/lib
38.60 MB  rubocop-ast/lib
31.62 MB  parser-3.2.1.0
31.43 MB  other
10.02 MB  lib
3.11 MB  rubocop-rspec-2.18.1
1.95 MB  rubocop-performance-1.16.0
1.83 MB  regexp_parser-2.7.0
1.61 MB  ast-2.4.2
405.71 …
```
> Performance and memory optimizations

- lib/rexml/parsers/xpathparser.rb
This adds support for a string literal that contains a double-quote to `XPathParser#abbreviate`. Basically any literal that contains a double-quote `"` must be quoted by single-quotes `'` since XPath 1.0 does not support any escape characters.
The change improves the following test script
```ruby
require 'rexml'
parsed = REXML::Parsers::XPathParser.new.parse('/a[b/text()=concat("c\'",\'"d\')]')
puts "#{parsed}"
puts ""
appreviated = REXML::Parsers::XPathParser.new.abbreviate parsed
puts "#{appreviated}"
```
```
[:document, :child, :qname, "", "a", :predicate, [:eq, [:child, :qname, "", "b", :child, :text], [:function, "concat", [[:literal, "c'"], [:literal, "\"d"]]]]]
/a[ b/text() = concat( "c'" , "\"d" ) ]
```
```
[:document, :child, :qname, "", "a", :predicate, [:eq, [:child, :qname, …
```
> xpath abbreviate: add support for string literal that contains double-quote

- .github/workflows/benchmark.yml
- Rakefile
- benchmark/parse.yaml
- rexml.gemspec
I want to improve the parsing process and would like to add a parsing benchmark.
The benchmark process just parses the XML from beginning to end.
Since performance differs depending on whether YJIT is ON or OFF, both are measured.
> Add parse benchmark

- benchmark/parse.yaml
- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- rexml.gemspec
- test/parse/test_entity_declaration.rb
- test/test_core.rb
Using StringScanner reduces the string copying process and speeds up the process.
And I removed unnecessary methods.
https://github.com/ruby/rexml/actions/runs/7549990000/job/20554906140?pr=105
```
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
rexml 3.2.6      master  3.2.6(YJIT)  master(YJIT) 
dom       4.868       5.077        8.137         8.303 i/s -     100.000 times in 20.540529s 19.696590s 12.288900s 12.043666s
sax      13.597      13.953       19.206        20.948 i/s -     100.000 times in 7.354343s 7.167142s 5.206745s 4.773765s
pull      15.641      16.918       22.266        25.378 i/s -     100.000 times in 6.393424s 5.910955s 4.491201s 3.940471s
stream      14.339      15.844       19.810        22.206 i/s - …
```
> Use string scanner with baseparser

- lib/rexml/parsers/baseparser.rb
Reduce calls to `Source#buffer`(`StringScanner#rest`)
`Source#buffer` calling `StringScanner#rest`.
`StringScanner#rest` is slow.
Reduce calls to `Source#buffer`.
```
dom     10.639      10.985        16.213       16.221 i/s -     100.000 times in 9.399033s 9.103461s 6.167962s 6.164794s
sax     28.357      29.440        42.900       44.375 i/s -     100.000 times in 3.526479s 3.396688s 2.331024s 2.253511s
pull     32.852      34.210        48.976       51.273 i/s - …
```
> Reduce calls to `Source#buffer`(`StringScanner#rest`)

- benchmark/parse.yaml
- lib/rexml/source.rb
- rexml.gemspec
JRuby's `StringScanner#<<` and `StringScanner#scan` OutOfMemoryError has been resolved in strscan gem 3.0.9.
https://github.com/ruby/strscan/issues/83
```
dom     10.958      11.044        16.615       16.783 i/s -     100.000 times in 9.126104s 9.055023s 6.018799s 5.958437s
sax     29.624      29.609        44.390       45.370 i/s -     100.000 times in 3.375641s 3.377372s 2.252774s 2.204080s
pull     33.868      34.695        51.173       53.492 i/s -     100.000 times in …
```
> Use `@scanner << readline` instead of `@scanner.string = @scanner.rest + readline`

- lib/rexml/parsers/baseparser.rb
`StringScanner.new()` instances can be reused within parse_attributes, reducing initialization costs.
```
dom     11.018      11.207        17.059       16.660 i/s -     100.000 times in 9.075992s 8.923280s 5.861969s 6.002555s
sax     29.843      30.821        45.518       47.505 i/s -     100.000 times in 3.350909s 3.244524s 2.196940s 2.105037s
pull     34.480      35.937        52.816       57.098 i/s -     100.000 times in 2.900205s 2.782632s 1.893370s 1.751378s
stream …
```
> Reduce calls to StringScanner.new()

- lib/rexml/parsers/baseparser.rb
loop is slower than `while true`.
```
dom     11.186      11.304        17.395       17.450 i/s -     100.000 times in 8.940144s 8.846590s 5.748718s 5.730793s
sax     30.811      31.629        47.352       48.040 i/s -     100.000 times in 3.245601s 3.161619s 2.111854s 2.081594s
pull     35.793      36.621        56.924       57.313 i/s -     100.000 times in 2.793829s 2.730693s 1.756732s 1.744812s
stream     33.157      34.757        46.792       50.536 i/s -     100.000 …
```
> Change loop in parse_attributes to `while true`.

- lib/rexml/functions.rb
- test/functions/test_base.rb
GitHub: fix GH-110
Fixed a bug in `REXML::Functions.normalize_space(array)` and introduced test cases for it:
- Corrected a typo in the variable name within the collect block (`string` -> `x`).
- Added `test_normalize_space_strings` to `test/functions/test_base.rb`.
> xpath: Fix normalize_space(array) case

- lib/rexml/parsers/baseparser.rb
https://github.com/ruby/rexml/blob/444c9ce7449d3c5a75ae50087555ec73ae1963a8/lib/rexml/parsers/baseparser.rb#L352-L425
```
next_data = @source.buffer
if next_data.size < 2
@source.read
next_data = @source.buffer
end
if next_data[0] == ?<
:
(omit)
:
else # next_data is a string of one or more characters other than '<'.
md = @source.match( TEXT_PATTERN, true ) # TEXT_PATTERN = /\A([^<]*)/um
text = md[1]
if md[0].length == 0 # md[0].length is greater than or equal to 1.
@source.match( /(\s+)/, true )
end
```
This is an unnecessary check because md[0].length is greater than or equal to 1.
> Remove unnecessary checks in baseparser

- benchmark/parse.yaml
Because benchmarks are broken when new strscan is released.
https://github.com/ruby/rexml/actions/runs/7825513689/job/21349811563
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/ruby -v -S benchmark-driver /home/runner/work/rexml/rexml/benchmark/parse.yaml
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
rexml 3.2.6      master  3.2.6(YJIT)  master(YJIT)
/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'strscan' (= 3.0.9) - did find: [strscan-3.1.0,strscan-3.0.7] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/runner/.local/share/gem/ruby/3.3.0:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0' , execute `gem env` for more …
```
> Stop specifying the gem version of strscan in benchmarks.

- test/functions/test_base.rb
- test/test_contrib.rb
- test/test_core.rb
- test/test_document.rb
- test/test_encoding.rb
- test/test_sax.rb
- test/test_validation_rng.rb
- test/test_xml_declaration.rb
- test/xpath/test_predicate.rb
XML declaration allowed only at the start of the document.
https://www.w3.org/TR/2006/REC-xml11-20060816/#document
```
[1]   document   ::=   ( prolog element Misc* ) - ( Char* RestrictedChar Char* ) 
```
It doesn't have `S*` before `prolog`.
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-prolog
```
[22]   prolog   ::=   	XMLDecl Misc* (doctypedecl Misc*)?
```
It doesn't have `S*` before `XMLdecl`.
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-XMLDecl
```
[23]   XMLDecl  ::=   '<?xml' VersionInfo EncodingDecl? SDDecl? S? '?>'
```
It doesn't have `S*` before `'<?xml'`.
> test: Fix invalid XML with spaces before the XML declaration

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- test/parse/test_document_type_declaration.rb
Improve maintainability by optimizing the process so that the parsing process proceeds using StringScanner#scan.
- Change `REXML::Parsers::BaseParser` from `frozen_string_literal: false` to `frozen_string_literal: true`.
- Added `Source#string=` method for error message output.
- Added TestParseDocumentTypeDeclaration#test_no_name test case.
- Of the `intSubset` of DOCTYPE, "<!" added consideration for processing `Comments` that begin with "<!".
```
dom     11.240      10.569 …
```
> Use more StringScanner based API to parse XML

- lib/rexml/source.rb
https://github.com/ruby/rexml/blob/370666e314816b57ecd5878e757224c3b6bc93f5/lib/rexml/source.rb#L208-L234
Because `@line_break = encode(">")`, the end of `@scanner << readline` is one of the following.
1. ">"
2. "X>"
3. "X" (eof)
This will not be matched by additional reads in the following cases.
- `@source.match("<?")`
- `@source.match("--")`
- `@source.match("DOCTYPE")`
In the following cases, additional reads may result in a match, but explicitly prohibiting such a specification with a comment makes the string length check unnecessary.
- `@source.match(">>")`
- `@source.match(">X")`
```
ruby 3.3.0 (2023-12-25 revision …
```
> source: Remove unnecessary string length comparisons in the case of string comparisons

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- test/parse/test_notation_declaration.rb
We want to just change scan pointer.
https://github.com/ruby/rexml/pull/114#discussion_r1501773803
> I want to just change scan pointer (`StringScanner#pos=`) instead of changing `@scanner.string`.
> Remove `Source#string=` method

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
It would affect performance to do a read check in `IOSource#match` every time, Separate read processing from `IOSource#ensure_buffer`.
Use `IOSource#ensure_buffer` in the following cases where `@source.buffer` is empty.
1. at the start of pull_event
2. If a trailing `'>'` pattern matches, as in `@source.match(/\s*>/um)`.
```
dom     10.278      10.986        16.430       16.941 i/s -     100.000 times in 9.729858s 9.102574s 6.086579s 5.902885s
sax     30.166      30.496 …
```
> Separate `IOSource#ensure_buffer` from `IOSource#match`.

- .github/workflows/test.yml
- test/formatter/test_default.rb
Ref: https://bugs.ruby-lang.org/issues/20205
Since `rexml` is tested as part of ruby-core CI, it needs to be compatible with the `--enable-frozen-string-literal` option.
> Make the test suite compatible with `--enable-frozen-string-literal`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_element.rb
- test/test_core.rb
Improve maintainability by consolidating processing into `Source#match`.
```
dom     10.891      10.622        16.356       17.403 i/s -     100.000 times in 9.182130s 9.414177s 6.113806s 5.746133s
sax     30.335      29.845        49.749       54.877 i/s -     100.000 times in 3.296483s 3.350595s 2.010071s 1.822259s
pull     35.514      34.801        61.123       66.908 i/s -     100.000 times in 2.815793s 2.873484s 1.636041s 1.494591s
stream     35.141      34.475 …
```
>  Optimize the parse_attributes method to use `Source#match` to parse XML. 

- lib/rexml/parsers/baseparser.rb
`attributes[name]` is faster than `attribute.has_key?(name)` in Micro Benchmark.
However, the Benchmark did not show a significant difference.
Would like to merge if possible, how about it?
See: https://github.com/ruby/rexml/pull/119#discussion_r1525611640
```
$ cat benchmark/attributes.yaml
loop_count: 100000
contexts:
- name: No YJIT
prelude: |
$LOAD_PATH.unshift(File.expand_path("lib"))
require 'rexml'
- name: YJIT
prelude: |
$LOAD_PATH.unshift(File.expand_path("lib"))
require 'rexml'
RubyVM::YJIT.enable
prelude: |
attributes = {}
name = :a
benchmark:
'attributes[name]' : attributes[name]
'attributes.has_key?(name)' : attributes.has_key?(name)
```
```
$ benchmark-driver benchmark/attributes.yaml
No YJIT        YJIT
attributes[name] …
```
> Change `attribute.has_key?(name)` to ` attributes[name]`.

- lib/rexml/xpath_parser.rb
- test/xpath/test_base.rb
Fixed incorrect calculation of position in node set.
See: https://github.com/ruby/rexml/issues/25
> xpath: Fix wrong position with nested path

- NEWS.md
It seems to me that mentioned in the NEWS.md and in the release notes PR #124 ("Move development dependencies to Gemfile") isn't a correct one and not related to CVE-2024-35176:
```
- Improved parse performance when an attribute has many <s.
- GH-124
```
#126 looks like fixes the issue with attribute value that contains multiple '>' characters. At least it adds a proper test.
> Fix the NEWS.md and change PR reference that fixes CVE-2024-35176

- lib/rexml/source.rb
Optimize `Source#read_until` method.
```
dom      9.877       9.992        15.605       17.559 i/s -     100.000 times in 10.124592s 10.008017s 6.408031s 5.695167s
sax     22.903      25.151        39.482       50.846 i/s -     100.000 times in 4.366300s 3.975922s 2.532822s 1.966706s
pull     25.940      30.474        44.685       61.450 i/s -     100.000 times in 3.855070s 3.281511s 2.237879s 1.627346s
stream     25.255      29.500        41.819       53.605 i/s - …
```
> Optimize Source#read_until method

- benchmark/parse.yaml
`.elements.each("root/child") {|_|}` is not a parsing operation.
```
dom     16.254      16.412        27.189       28.940 i/s -     100.000 times in 6.152343s 6.093050s 3.677924s 3.455456s
sax     22.909      23.194        39.481       40.099 i/s -     100.000 times in 4.365165s 4.311414s 2.532840s 2.493807s
pull     26.281      25.918        44.465       45.733 i/s -     100.000 times in 3.805063s 3.858328s 2.248968s 2.186621s
stream     25.196      25.185        41.674 …
```
> benchmark: Remove non-parsing operations from the DOM case

- benchmark/each_recursive.yaml
- lib/rexml/node.rb
- test/test_document.rb
Fix #134
This PR does:
- Add `benchmark/each_recursive.yaml`
- Rewrite `Node#each_recursive` implementation for performance
- Add a test for `Node#each_recursive`
The performance of `Node#each_recursive` is improved 60~80x faster.
`each_recursive` is too much slow as I described in #134.
I improved this performance by rewriting its implementation in this PR.
Also, I added a benchmark in `benchmark/each_recursive.yaml` and the following is a result on my laptop:
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /Users/makenowjust/Projects/github.com/makenowjust/simple-dotfiles/.asdf/installs/ruby/3.3.2/bin/ruby -v -S benchmark-driver /Users/makenowjust/Projects/github.com/ruby/rexml/benchmark/each_recursive.yaml
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin23]
Calculating …
```
> Improve `Node#each_recursive` performance

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
This check was missing. Therefore, `REXML::Document.new("<!--")` raised the ``undefined method `[]' for nil`` error, for example.
This PR also adds tests for "malformed comment" checks.
> Add a "malformed comment" check for top-level comments

- benchmark/attribute.yaml
- lib/rexml/element.rb
`Element#namespaces` is heavy method because this method needs to traverse all ancestors of the element. `Element#attribute` calls `namespaces` redundantly, so it is much slower.
This PR reduces `namespaces` calls in `Element#attribute`. Also, this PR removes a redundant `respond_to?` because `namespaces` must return `Hash` in the current implementation.
Below is the result of a benchmark for this on my laptop.
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /Users/makenowjust/Projects/github.com/makenowjust/simple-dotfiles/.asdf/installs/ruby/3.3.2/bin/ruby -v -S benchmark-driver /Users/makenowjust/Projects/github.com/ruby/rexml/benchmark/attribute.yaml
ruby 3.3.2 (2024-05-30 revision e5a195edf6) [arm64-darwin23]
rexml 3.2.6      master  3.2.6(YJIT) …
```
> Improve `Element#attribute` implementation as 6500x faster

- test/test_document.rb
- test/test_light.rb
- test/test_sax.rb
- test/xpath/test_base.rb
I found these typos with using [`typos-cli`](https://github.com/crate-ci/typos).
Now, we can obtain no typo reports from the `typos` command with this configuration (`.typos.toml`):
```toml
[files]
extend-exclude = [
"*.svg",
"*.xml",
]
[default.extend-words]
arry = "arry"
blok = "blok"
eles = "eles"
caf = "caf"
abl = "abl" # NOTE: It is a part of "Ablüfe".
alle = "alle"
ist = "ist"
technik = "technik"
```
Thank you.
> Fix small typos

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
`Document.new("<a><!-->")` raises `undefined method '[]' for nil`. This commit fixes it and adds a test for it.
> Add a "Malformed comment" check for invalid comments such as `<!-->`

- lib/rexml/parsers/baseparser.rb
- lib/rexml/parsers/treeparser.rb
- test/parse/test_document_type_declaration.rb
> Reject unclosed DOCTYPE on parsing

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- test/parser/test_base_parser.rb
GitHub: fix GH-150
If a parsed XML is later than `2 ** 31 - 1`, we can't parse it. Because `StringScanner`s position is stored as `int`. We can avoid the restriction by dropping large parsed content.
> Fix a bug that a large XML can't be parsed

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
Included constants are not private. So private constants in private module aren't private.
See also: https://github.com/ruby/rexml/pull/154#discussion_r1649469269
> Don't include private_constant-ed module

- rexml.gemspec
Supported here: https://guides.rubygems.org/specification-reference/#metadata 
Useful for running https://github.com/MaximeD/gem_updater
> Add changelog_uri to gemspec

- lib/rexml/parsers/baseparser.rb
`Set.new()` instances of the prefixes variable can be reused, reducing initialization costs.
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /Users/naitoh/.rbenv/versions/3.3.3/bin/ruby -v -S benchmark-driver /Users/naitoh/ghq/github.com/naitoh/rexml/benchmark/parse.yaml
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [arm64-darwin22]
dom     17.714      17.658        32.898       33.247 i/s -     100.000 times in 5.645176s 5.663160s 3.039707s 3.007755s
sax     25.280      25.281        47.483       49.990 i/s -     100.000 times in 3.955694s 3.955534s 2.106006s 2.000389s
pull     29.048      29.061        59.944       61.498 i/s -     100.000 times in 3.442599s 3.441014s 1.668222s 1.626060s
stream     28.181 …
```
> Reuse of Set.new at prefixes variables

- lib/rexml/parsers/baseparser.rb
- test/test_pullparser.rb
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /Users/naitoh/.rbenv/versions/3.3.3/bin/ruby -v -S benchmark-driver /Users/naitoh/ghq/github.com/naitoh/rexml/benchmark/parse.yaml
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [arm64-darwin22]
dom     17.704      18.106        34.215       33.806 i/s -     100.000 times in 5.648398s 5.523110s 2.922698s 2.958036s
sax     25.664      25.302        48.429       48.602 i/s -     100.000 times in 3.896488s 3.952289s 2.064859s 2.057537s
pull     28.966      29.215        61.710       62.068 i/s -     100.000 times in 3.452275s 3.422901s 1.620480s 1.611129s
stream     28.291      28.426        53.860       55.548 i/s -     100.000 times in 3.534716s 3.517884s …
```
> Optimize BaseParser#unnormalize method

- lib/rexml/parsers/baseparser.rb
- test/test_pullparser.rb
See: https://github.com/ruby/rexml/pull/158#issuecomment-2187663068
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /Users/naitoh/.rbenv/versions/3.3.3/bin/ruby -v -S benchmark-driver /Users/naitoh/ghq/github.com/naitoh/rexml/benchmark/parse.yaml
ruby 3.3.3 (2024-06-12 revision f1c7b6f435) [arm64-darwin22]
dom     17.674      17.567        32.759       32.316 i/s -     100.000 times in 5.657973s 5.692371s 3.052595s 3.094448s
sax     25.261      25.377        48.889       49.911 i/s -     100.000 times in 3.958626s 3.940640s 2.045460s 2.003575s
pull     28.968      29.121        61.584       61.774 i/s -     100.000 times in 3.452132s 3.433967s 1.623789s 1.618809s
stream     28.395      28.803        55.289 …
```
> Optimize BaseParser#unnormalize method to replace "\r\n" with "\n" only when "\r\n" is included

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
- test/parse/test_element.rb
- test/parse/test_processing_instruction.rb
- test/parse/test_text.rb
- test/test_pullparser.rb
XML with additional content at the end of the document is invalid.
https://www.w3.org/TR/2006/REC-xml11-20060816/#document
```
[1]   document   ::=   ( prolog element Misc* ) - ( Char* RestrictedChar Char* )
```
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-Misc
```
[27]    Misc       ::=          Comment | PI | S
```
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-PI
```
[16]    PI         ::=          '<?' PITarget (S (Char* - (Char* '?>' Char*)))? '?>'
```
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-PITarget
```
[17]    PITarget           ::=          Name - (('X' | 'x') ('M' | 'm') ('L' | 'l'))
```
> fix: Extra content at the end of the document

- lib/rexml/parsers/baseparser.rb
- test/parse/test_processing_instruction.rb
XML declaration must be the first item.
https://www.w3.org/TR/2006/REC-xml11-20060816/#document
```
[1]   document   ::=   ( prolog element Misc* ) - ( Char* RestrictedChar Char* )
```
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-prolog
```
[22]   prolog   ::=   	XMLDecl Misc* (doctypedecl Misc*)?
```
https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-XMLDecl
```
[23]   XMLDecl  ::=   '<?xml' VersionInfo EncodingDecl? SDDecl? S? '?>'
```
See: https://github.com/ruby/rexml/pull/161#discussion_r1666118193
> Add position check for XML declaration

- lib/rexml/formatters/pretty.rb
- test/test_document.rb
If the XML file does not end with a newline, a space is added to the end of the first line.
```ruby
Failure: test_indent(REXMLTests::TestDocument::WriteTest::ArgumentsTest)
/Users/naitoh/ghq/github.com/naitoh/rexml/test/test_document.rb:270:in `test_indent'
267:           output = ""
268:           indent = 2
269:           @document.write(output, indent)
=> 270:           assert_equal(<<-EOX.chomp, output)
271: <?xml version='1.0' encoding='UTF-8'?>
272: <message>
273:   Hello world!
<"<?xml version='1.0' encoding='UTF-8'?>\n" +
"<message>\n" +
"  Hello world!\n" +
"</message>"> expected but was
<"<?xml version='1.0' encoding='UTF-8'?> \n" +
"<message>\n" +
"  Hello world!\n" +
"</message>">
diff:
? <?xml version='1.0' encoding='UTF-8'?>
<message>
Hello world!
</message>
```
This is …
> Stop adding extra new line after XML declaration with pretty format

- test/test_text_check.rb
This patch will add missing REXML::Text.check tests.
This is the tests for the part that is checked using a regular expression:
https://github.com/ruby/rexml/blob/b2ec329dc1dc7635b224a6d61687c24b1e1db6fd/lib/rexml/text.rb#L155-L172
> Add tests for REXML::Text.check

- test/test_text_check.rb
This patch will fix incorrect string in a case where unicode characters.
Because of the use of single quotes, it was simply an ASCII string.
> Fix test for Text.check

- lib/rexml/parsers/baseparser.rb
- test/parse/test_text.rb
- test/parser/test_ultra_light.rb
- test/test_core.rb
- test/test_document.rb
GitHub: fix GH-163
- sax_test.rb
```
require 'rexml/parsers/sax2parser'
require 'rexml/parsers/pullparser'
require 'rexml/parsers/streamparser'
require 'libxml-ruby'
require 'nokogiri'
xml = <<EOS
<root> a b  c
</root>
<?abc version="1.0" ?>
EOS
class Listener
def method_missing(name, *args)
p [name, *args]
end
end
puts "LibXML(SAX)"
parser = LibXML::XML::SaxParser.string(xml)
parser.callbacks = Listener.new
parser.parse
puts ""
puts "Nokogiri(SAX)"
parser = Nokogiri::XML::SAX::Parser.new(Listener.new)
parser.parse(xml)
puts ""
puts "REXML(SAX)"
parser = REXML::Parsers::SAX2Parser.new(xml)
parser.listen(Listener.new)
parser.parse
puts ""
puts "REXML(Pull)"
parser = REXML::Parsers::PullParser.new(xml)
while parser.has_next?
res = parser.pull
p res
end
puts ""
puts "REXML(Stream)"
parser = …
```
> Do not output :text event after the root tag is closed

- lib/rexml/parsers/sax2parser.rb
- lib/rexml/parsers/streamparser.rb
- test/test_pullparser.rb
- test/test_sax.rb
SAX2 parser expand user-defined entity references and character references but doesn't expand predefined entity references.
- text_unnormalized.rb
```
require 'rexml/document'
require 'rexml/parsers/sax2parser'
require 'rexml/parsers/pullparser'
require 'rexml/parsers/streamparser'
xml = <<EOS
<root>
<A>&lt;P&gt;&https://github.com/ruby/rexml/pull/13; &lt;I&gt; &lt;B&gt; Text &lt;/B&gt;  &lt;/I&gt;</A>
</root>
EOS
class Listener
def method_missing(name, *args)
p [name, *args]
end
end
puts "REXML(DOM)"
REXML::Document.new(xml).elements.each("/root/A") {|element| puts element.text}
puts ""
puts "REXML(Pull)"
parser = REXML::Parsers::PullParser.new(xml)
while parser.has_next?
res = parser.pull
p res
end
puts ""
puts "REXML(Stream)"
parser = REXML::Parsers::StreamParser.new(xml, …
```
> Fix a bug that SAX2 parser doesn't expand the predefined entities for "characters"

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- test/parse/test_processing_instruction.rb
> Fix performance issue caused by using repeated `>` characters inside `<?xml`

- lib/rexml/text.rb
- test/parse/test_character_reference.rb
This patch will fix the ReDoS that is caused by large string of 0s on a character reference (like `&#00000000...`).
This is occurred in Ruby 3.1 or earlier.
> Fix ReDoS caused by very large character references using repeated 0s

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
> Fix performance issue caused by using repeated `>` characters inside comments

- lib/rexml/parsers/baseparser.rb
- test/parse/test_cdata.rb
> Fix performance issue caused by using repeated `>` characters inside `CDATA [ PAYLOAD ]`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_document_type_declaration.rb
> Fix performance issue caused by using repeated `>` characters after ` <!DOCTYPE name`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_document_type_declaration.rb
> Fix performance issue caused by using repeated `>` characters inside `<!DOCTYPE root [<!-- PAYLOAD -->]>`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_entity_declaration.rb
> Fix performance issue caused by using repeated `>` characters inside `<!DOCTYPE name [<!ENTITY>]>`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_attlist.rb
Fix performance by removing unnecessary spaces.
This is occurred in Ruby 3.1 or earlier.
> Fix ReDoS by using repeated space characters inside `<!DOCTYPE name [<!ATTLIST>]>`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
> Fix performance issue caused by using repeated `>` characters inside `<xml><!-- --></xml>`

- lib/rexml/parsers/baseparser.rb
- test/parse/test_entity_declaration.rb
This PR includes following two fixes.
1. The `test_empty` and `test_linear_performance_gt` were defined as private method. Seems that test-unit runner does not invoke private methods even if the methods have `test_` prefix.
2. When parse malformed entity declaration, the exception might have the message about `NoMethodError`. The proper exception message will be contained by this fix.
> Fix method scope in test in order to invoke the tests properly and fix exception message

- test/parse/test_entity_declaration.rb
This patch will add the test cases to verify that it raises an exception properly when parsing malformed entity declaration.
> Add more invalid test cases for  parsing entitly declaration

- lib/rexml/parsers/baseparser.rb
- lib/rexml/parsers/pullparser.rb
- lib/rexml/parsers/sax2parser.rb
- test/test_document.rb
- test/test_pullparser.rb
- test/test_sax.rb
- Supported `REXML::Security.entity_expansion_limit=` in SAX and Pull
- Supported `REXML::Security.entity_expansion_text_limit=` in SAX and Pull
> Add support for XML entity expansion limitation in SAX and pull parsers

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
Performance problem of `source.match(regexp)` was recently fixed by specifying terminator string. However, I think maintaining appropriate terminator string for a regexp is hard.
I propose solving this performance issue by increasing bytes to read in each iteration.
> Fix source.match performance without specifying term string

- lib/rexml/parsers/baseparser.rb
`REXML::Parser::BaseParser` uses `REXML::Security` since #187. But `rexml/parsers/baseparser.rb` doesn't require `rexml/security` explicitly.
This doesn't cause a problem in normal usages because `require "rexml"` requires `rexml/security` implicitly. If an user requires specific parser such as `rexml/parsers/streamparser` explicitly, this causes a problem.
We should require `rexml/security` explicitly in `rexml/parsers/baseparser.rb` explicitly because `REXML::Parser::BaseParser` uses `REXML::Security`.
When `lib/rexml/parsers/baseparser.rb` is required directly, the `REXML::Security` module is not required. It causes the following error:
```ruby
require "rexml/parsers/streamparser"
require "rexml/streamlistener"
class Listener
include REXML::StreamListener
end …
```
> Add missing rexml/security require in rexml/parsers/baseparser.rb

- lib/rexml/parsers/baseparser.rb
- test/test_document.rb
- test/test_pullparser.rb
- test/test_sax.rb
GitHub: fix #193
In SAX and pull parsers, the total value of rv.bytesize was checked, but the summing process was unnecessary.
- Add Log
```patch
diff --git a/lib/rexml/parsers/baseparser.rb b/lib/rexml/parsers/baseparser.rb
index 28810bf..5cfc089 100644
--- a/lib/rexml/parsers/baseparser.rb
+++ b/lib/rexml/parsers/baseparser.rb
@@ -556,6 +556,7 @@ module REXML
re = Private::DEFAULT_ENTITIES_PATTERNS[entity_reference] || /&#{entity_reference};/
rv.gsub!( re, entity_value )
sum += rv.bytesize
+puts " rv.bytesize: #{rv.bytesize} sum: #{sum} > Security.entity_expansion_text_limit: #{Security.entity_expansion_text_limit} : #{rv}"
if sum > Security.entity_expansion_text_limit
raise "entity expansion has grown too large"
end
diff --git a/lib/rexml/text.rb b/lib/rexml/text.rb
index …
```
> Fix calculation of Security.entity_expansion_text_limit in SAX/pull parsers

- lib/rexml/parsers/baseparser.rb
- test/test_pullparser.rb
- test/test_sax.rb
The current implementation of `#unnormalize` iterates over matched entity references that already has been substituted. With these changes we will reduce the number of redundant calls to `rv.gsub!`.
* Reject filtered matches earlier in the loop
* Improve `#unnormalize` by removing redundant calls to `rv.gsub!`
* Improve `entity_expansion_limit` tests
---
Example:
```ruby
require "rexml/parsers/baseparser"
entity_less_than = "&lt;"
entitiy_length = 100
filler_text = "A"
filler_length = 100
feed = "#{entity_less_than * entitiy_length}#{filler_text * filler_length}"
base_parser = REXML::Parsers::BaseParser.new("")
base_parser.unnormalize(feed) # => "<" * 100 + "A" * 100
```
Before this PR, the example above would require 100 iterations. After this PR, 1 iteration.
> Improve `BaseParser#unnormalize`

- lib/rexml/parsers/baseparser.rb
- test/test_pullparser.rb
- test/test_sax.rb
- test/test_stream.rb
* Change `#entity` to not match against default entities
After this change, the following example will not raise a RuntimeError:
```ruby
$LOAD_PATH.unshift(File.expand_path("lib"))
require "rexml/parsers/baseparser"
valid_feed = "&lt;p&gt;#{'A' * 10_240}&lt;/p&gt;"
base_parser = REXML::Parsers::BaseParser.new("")
base_parser.unnormalize(valid_feed) # => "<p>" + "A" * 10_240 + "</p>"
```
Default entities now gets substituted by this block instead
https://github.com/ruby/rexml/blob/e14847cee53d26eb162ad786ba12e3cd7a86fce0/lib/rexml/parsers/baseparser.rb#L560-L563
Close #198
> Fix RuntimeError in `REXML::Parsers::BaseParser` for valid feeds

- lib/rexml/entity.rb
- lib/rexml/parsers/baseparser.rb
- test/test_document.rb
- test/test_entity.rb
In the internal subset of DTD, references to parameter entities are not allowed within markup declarations.
See: https://www.w3.org/TR/xml/#wfc-PEinInternalSubset
> Well-formedness constraint: PEs in Internal Subset
> In the internal DTD subset, parameter-entity references MUST NOT occur within markup declarations; they may occur where markup declarations can occur. (This does not apply to references that occur in external parameter entities or to the external subset.)
> Fix to not allow parameter entity references at internal subsets

- lib/rexml/parsers/streamparser.rb
- test/test_stream.rb
Pull parser expands character references and predefined entity references, but doesn't expand user-defined entity references.
- text_stream_unnormalize.rb
```
$LOAD_PATH.unshift(File.expand_path("lib"))
require 'rexml/document'
require 'rexml/parsers/sax2parser'
require 'rexml/parsers/pullparser'
require 'rexml/parsers/streamparser'
require 'rexml/streamlistener'
xml = <<EOS
<!DOCTYPE foo [
<!ENTITY la "1234">
<!ENTITY lala "--&la;--">
<!ENTITY lalal "&la;&la;">
]><root><la>&la;</la><lala>&lala;</lala><a>&lt;P&gt; &lt;I&gt; &lt;B&gt; Text &lt;/B&gt; &lt;/I&gt;</a><b>test&#8482;</b></root>
EOS
class StListener
include REXML::StreamListener
def text(text)
puts text
end
end
puts "REXML(DOM)"
REXML::Document.new(xml).elements.each("/root/*") {|element| puts element.text}
puts ""
puts …
```
> Fix a bug that Stream parser doesn't expand the user-defined entity references for "text"

- lib/rexml/attribute.rb
- lib/rexml/document.rb
- lib/rexml/entity.rb
- lib/rexml/parsers/baseparser.rb
- lib/rexml/parsers/pullparser.rb
- lib/rexml/parsers/sax2parser.rb
- lib/rexml/parsers/streamparser.rb
- lib/rexml/text.rb
- test/test_document.rb
- test/test_pullparser.rb
- test/test_sax.rb
- test/test_stream.rb
GitHub: fix GH-192
Add local entity expansion limit methods.
- `REXML::Document#entity_expansion_limit=`
- `REXML::Document#entity_expansion_text_limit=`
- `REXML::Parsers::SAX2Parser#entity_expansion_limit=`
- `REXML::Parsers::SAX2Parser#entity_expansion_text_limit=`
- `REXML::Parsers::StreamParser#entity_expansion_limit=`
- `REXML::Parsers::StreamParser#entity_expansion_text_limit=`
- `REXML::Parsers::PullParser#entity_expansion_limit=`
- `REXML::Parsers::PullParser#entity_expansion_text_limit=`
> Add local entity expansion limit methods

- rexml.gemspec
See discussion in #140. `strscan` is a part of the Ruby standard library in all versions of Ruby supported by REXML.
Fixes #140.
> Remove strscan dependency declaration from gemspec

- lib/rexml/parsers/sax2parser.rb
- test/test_sax.rb
```
dom     18.085      17.677        33.086       32.778 i/s -     100.000 times in 5.529372s 5.657097s 3.022471s 3.050832s
sax     25.450      26.182        44.797       47.916 i/s -     100.000 times in 3.929249s 3.819475s 2.232309s 2.086982s
pull     29.160      29.089        55.407       53.531 i/s -     100.000 times in 3.429304s 3.437757s 1.804825s 1.868072s
stream     29.137      29.055        52.780       51.368 i/s -     100.000 times in 3.432007s 3.441754s …
```
> Optimize SAX2Parser#get_namespace

- lib/rexml/parsers/baseparser.rb
- test/parser/test_base_parser.rb
Hello,
I found parsing XHTML documents like below fails since v3.3.3:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>XHTML Document</title>
</head>
<body>
<h1>XHTML Document</h1>
<p xml:lang="ja" lang="ja">この段落は日本語です。</p>
</body>
</html>
```
[XML namespace spec][spec] is a little bit ambiguous but document above is valid according to an [article W3C serves][article].
I fixed the parsing algorithm. Can you review it?
As an aside, `<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">` style language declaration is often used in XHTML files included in EPUB files because [sample EPUB files][samples] provided by IDPF, former EPUB spec authority, use the style.
[spec]: …
> Fix handling with "xml:" prefixed namespace

- lib/rexml/source.rb
- test/test_document.rb
The result of `encode(term)` can be cached.
```
dom     17.546      18.512        32.282       32.306 i/s -     100.000 times in 5.699323s 5.402026s 3.097658s 3.095448s
sax     25.435      28.294        47.526       50.074 i/s -     100.000 times in 3.931613s 3.534310s 2.104122s 1.997057s
pull     29.471      31.870        54.400       57.554 i/s -     100.000 times in 3.393211s 3.137793s 1.838222s 1.737494s
stream     29.169      31.153        51.613       52.898 i/s - …
```
> Optimize `IOSource#read_until` method

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- test/parse/test_text.rb
Fixed a problem that `@pending_buffer` is not processed when `IOError` occurs in `@source.readline` although `@pending_buffer` exists when reading XML file.
> Fix `IOSource#readline` for `@pending_buffer`

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
`StringScanner#match?` is faster than `StringScanner#check`.
See: https://github.com/ruby/strscan/pull/111
```
dom     18.819      19.362        32.846       34.708 i/s -     100.000 times in 5.313905s 5.164791s 3.044500s 2.881200s
sax     28.188      29.982        48.386       52.554 i/s -     100.000 times in 3.547597s 3.335304s 2.066732s 1.902809s
pull     31.962      33.902        57.868       60.662 i/s -     100.000 times in 3.128689s 2.949690s 1.728071s 1.648467s …
```
> Add `IOSource#match?` method

- lib/rexml/source.rb
> Clarify variable name

- lib/rexml/source.rb
`SourceFactory::create_from(String)` will always run the `require 'stringio'` operation. This prevents a multi-threaded JRuby application from parsing xml on separate threads concurrently given that `require` will pass through a synchronized piece of code.
An experiment in removing this `require` lead to a 10x performance improvement on 10 threads parsing incoming strings on xml. For more details see https://github.com/logstash-plugins/logstash-filter-xml/issues/83
> Stop requiring stringio dynamically

- lib/rexml/parsers/baseparser.rb
- lib/rexml/parsers/pullparser.rb
- test/test_pullparser.rb
GitHub: Fix GH-214 
This is for parsing XML documents stream. We can use one parser to parse multiple XML documents with this feature.
> parser pull: Add support for reusing parser

- lib/rexml/source.rb
- test/parse/test_text.rb
If via IO.pipe, `IOError` exception is not raised, but `Errno::ESPIPE` or `Errno::EPIPE` or `Errno::EINVAL` exception is raised.
- CRuby
```
@er_source.pos
#=> Errno::ESPIPE Exception: Illegal seek
```
- CRuby (Windows (Ruby 2.6 or earlier))
```
@er_source.pos
#=> Errno::EINVAL: Invalid argument
```
- JRuby
```
@er_source.pos
#=> Errno::EPIPE: Broken pipe - No message available
```
> Fix error handling when parsing XML via IO.pipe

- test/parse/test_character_reference.rb
This commit fixes the following NameError when running only specific test file test/parse/test_character_reference.rb.
```
$ ruby test/parse/test_character_reference.rb -v
Loaded suite test/parse/test_character_reference
Started
REXMLTests::TestParseCharacterReference:
test_hex_precedding_zero:           E
===========================================================================================
Error: test_hex_precedding_zero(REXMLTests::TestParseCharacterReference): NameError: uninitialized constant REXML::Parsers::PullParser
test/parse/test_character_reference.rb:18:in 'REXMLTests::TestParseCharacterReference#test_hex_precedding_zero'
===========================================================================================
: (0.001470)
test_linear_performance_many_preceding_zeros: …
```
> test: Fix NameError: uninitialized constant REXML::Parsers::PullParser

- lib/rexml/text.rb
`String#encode` is supported in Ruby 1.9 and later.
> Remove old code for Ruby 1.8

- lib/rexml/source.rb
`StringScanner#check_until(string)` is faster than `StringScanner#check_until(regex)`.
See:
- https://github.com/ruby/strscan/pull/106
- https://github.com/ruby/strscan/pull/111
```
dom     19.459      19.840        35.035       35.786 i/s -     100.000 times in 5.139034s 5.040369s 2.854304s 2.794367s
sax     30.057      30.026        52.986       53.716 i/s -     100.000 times in 3.326998s 3.330499s 1.887303s 1.861652s
pull     33.777      34.415        62.294       64.020 …
```
> Optimize `IOSource#read_until` method by using `StringScanner#check_until(string)`

- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
`StringScanner#peek_byte` is fast, because it does not generate String object.
```
dom     19.753      19.888        35.641       35.928 i/s -     100.000 times in 5.062402s 5.028121s 2.805792s 2.783339s
sax     30.349      30.978        53.485       57.885 i/s -     100.000 times in 3.295012s 3.228103s 1.869671s 1.727567s
pull     34.170      35.436        61.713       66.534 i/s -     100.000 times in 2.926534s 2.821955s 1.620404s 1.502996s
stream     33.121      35.268 …
```
> Use `StringScanner#peek_byte` to get double or single quotation mark

- Gemfile
Ruby 3.5+ requires that rdoc explicitly be declared as a dependency
Should sort out GitHub Actions that are failing due to this
> Added rdoc as a development dependency (for Ruby 3.5+)

- Gemfile
- lib/rexml/parsers/baseparser.rb
- test/test_core.rb
GitHub: fix #233
Changed so that "<!ATTLIST" is added to AttDecl contents - simliar to how it already was with "<!ENTITY"
Updated a test case to test for this
> Fix serialization of ATTLIST is incorrect

- .github/workflows/benchmark.yml
Ruby 3.4 has been released, we will change our benchmark target to Ruby latest(3.4).
> Changed benchmark target to Ruby latest

- lib/rexml/parsers/baseparser.rb
- test/parse/test_document_type_declaration.rb
```
RUBYLIB= BUNDLER_ORIG_RUBYLIB= /Users/naitoh/.rbenv/versions/3.4.1/bin/ruby -v -S benchmark-driver /Users/naitoh/ghq/github.com/naitoh/rexml/benchmark/parse.yaml
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
dom     19.849      20.109        36.064       38.655 i/s -     100.000 times in 5.038102s 4.972864s 2.772838s 2.586981s
sax     30.339      30.449        52.946       54.873 i/s -     100.000 times in 3.296102s 3.284176s 1.888722s 1.822391s
pull     34.785      34.916        65.808       65.219 i/s -     100.000 times in 2.874810s 2.863976s 1.519581s 1.533305s
stream     34.766      34.921        61.920       63.277 i/s -     100.000 times in 2.876359s 2.863571s …
```
> Reduced regular expression processing in the form of processing white space first

- benchmark/parse_cdata.yaml
- lib/rexml/parsers/baseparser.rb
- lib/rexml/source.rb
- test/parse/test_cdata.rb
GitHub: fix #243
```
$ benchmark-driver benchmark/parse_cdata.yaml
rexml 3.4.1      master  3.4.1(YJIT)  master(YJIT)
dom     648.361      1.178k      591.590        1.046k i/s -     100.000 times in 0.154235s 0.084913s 0.169036s 0.095627s
sax     699.061      1.378k      651.148        1.196k i/s -     100.000 times in 0.143049s 0.072549s 0.153575s 0.083611s
pull     699.271      1.379k      660.275        1.210k i/s -     100.000 times in 0.143006s 0.072527s 0.151452s 0.082622s
stream     701.725      1.383k      659.483        1.228k i/s -     100.000 times in 0.142506s 0.072307s 0.151634s 0.081455s
Comparison:
dom
master:      1177.7 i/s
master(YJIT):      1045.7 i/s - 1.13x  slower
rexml 3.4.1:       648.4 i/s - 1.82x  slower …
```
> Improve CDATA parse performance

- benchmark/parse_comment.yaml
- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
```
$ benchmark-driver benchmark/parse_comment.yaml
rexml 3.4.1      master  3.4.1(YJIT)  master(YJIT)
top_level     999.440      5.058k      922.416        3.340k i/s -     100.000 times in 0.100056s 0.019770s 0.108411s 0.029936s
in_doctype      1.063k      4.890k      980.498        3.341k i/s -     100.000 times in 0.094116s 0.020449s 0.101989s 0.029927s
after_doctype     638.321      1.304k      603.952        1.153k i/s -     100.000 times in 0.156661s 0.076710s 0.165576s 0.086748s
Comparison:
top_level
master:      5058.2 i/s
master(YJIT):      3340.5 i/s - 1.51x  slower
rexml 3.4.1:       999.4 i/s - 5.06x  slower
3.4.1(YJIT):       922.4 i/s - 5.48x  slower
in_doctype
master:      4890.2 i/s
master(YJIT):      3341.5 i/s - 1.46x …
```
> Improve comment parse performance

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
Since `<a><!a` and `<a><!a>` are malformed node, they do not need to be checked before comments and CDATA.
```
$ benchmark-driver benchmark/parse_comment.yaml
after_doctype     1.306k      5.586k        1.152k       3.569k i/s -     100.000 times in 0.076563s 0.017903s 0.086822s 0.028020s
Comparison:
after_doctype
after:      5585.7 i/s
after(YJIT):      3568.9 i/s - 1.57x  slower
before:      1306.1 i/s - 4.28x  slower
before(YJIT):      1151.8 i/s - 4.85x  slower
```
- YJIT=ON : 3.09x faster
- YJIT=OFF : 4.28x faster
```
$ benchmark-driver benchmark/parse_cdata.yaml
dom     1.269k      5.548k …
```
> Improve CDATA and comment parse performance

- lib/rexml/parsers/baseparser.rb
- test/parse/test_comment.rb
Added exception to make the process easier to understand.
> Raise appropriate exception when failing to match start tag in DOCTYPE

- NEWS.md
I think the mentioned of CVE-2024-35176 in NEWS.md is incorrect.
```
- Improved parse performance when an attribute has many <s.
- GH-126
```
#126 looks like fixes the issue with attribute value that contains multiple '>' characters.
> NEWS.md : Fix the mentioned of the PR in CVE-2024-35176.

- lib/rexml/xpath_parser.rb
- test/xpath/test_base.rb
The code below was failing with `REXML::XPathParser#sort': undefined method '-@' for an instance of Array`
```ruby
d = REXML::Document.new("<a><b><c/><d/><x/></b><b><e/><x/></b></a>")
matches = REXML::XPath.match(d, "a/b/x/preceding-sibling::node()")
```
This pull request will fix it.
> Fix reverse sort in xpath_parser

- lib/rexml/xpath.rb
- lib/rexml/xpath_parser.rb
- test/test_jaxen.rb
- test/xpath/test_base.rb
`XPath.match`, `XPath.first`, `XPath.each`, `XPathParser#parse` and `XPathParser#match` accepted nodeset as element.
This pull request changes the first parameter of these method to be an element instead of nodeset.
Passing nodeset will be deprecated.
```ruby
REXML::XPath.match(element, xpath)
nodeset = [element]
REXML::XPath.match(nodeset, xpath)
```
#249 will introduce a temporary cache.
```ruby
def parse path, nodeset
path_stack = @parser.parse( path )
nodeset.first.document.send(:enable_cache) do
match( path_stack, nodeset )
end
end
```
But the signature `XPathParser#match(path, nodeset)` does not guarantee that all nodes in the nodeset has the same root document.
So cache does not work in the code below. It's still slow.
```ruby
REXML::XPath.match(2.times.map { …
```
> Deprecate accepting array as an element in XPath.match, first and each

- benchmark/xpath.yaml
- lib/rexml/attribute.rb
- lib/rexml/document.rb
- lib/rexml/element.rb
- lib/rexml/xpath_parser.rb
- test/test_core.rb
- test/xpath/test_base.rb
When using `//` in XPath, the deeper the tag hierarchy, the slower it becomes due to the namespace acquisition process.
Caching namespace information improves performance when using `//` with XPath.
```
$ benchmark-driver benchmark/xpath.yaml
rexml 3.4.1      master  3.4.1(YJIT)  master(YJIT)
REXML::XPath.match(REXML::Document.new(xml), 'a//a')      29.215     234.909      108.945       492.410 i/s -     100.000 times in 3.422925s 0.425697s 0.917898s 0.203083s
Comparison:
REXML::XPath.match(REXML::Document.new(xml), 'a//a')
master(YJIT):       492.4 i/s
master:       234.9 i/s - 2.10x  slower
3.4.1(YJIT):       108.9 i/s - 4.52x  slower
rexml 3.4.1:        29.2 i/s - 16.85x  slower
```
- YJIT=ON : 4.52x faster
- YJIT=OFF : 8.04x faster
> Improve using `//` in XPath performance

- lib/rexml/attribute.rb
- lib/rexml/text.rb
- test/test_text_check.rb
The doctype parameter of Text.check is not being used.
Changing the doctype parameter to an optional parameter improves the parsing speed of the DOM.
```
dom     19.854      23.805        33.969       37.712 i/s -     100.000 times in 5.036779s 4.200839s 2.943877s 2.651709s
sax     29.436      30.494        54.070       55.089 i/s -     100.000 times in 3.397155s 3.279348s 1.849463s 1.815255s
pull     34.908      34.857        62.969       64.895 i/s -     100.000 times in 2.864651s 2.868842s 1.588082s 1.540939s
stream     34.570      34.281        60.616       60.355 i/s -     100.000 times in 2.892656s 2.917080s 1.649737s 1.656866s
Comparison:
dom
after(YJIT):        37.7 i/s
before(YJIT):        34.0 i/s - 1.11x  slower
after:        23.8 …
```
> Improve `Text.check` performance

- lib/rexml/xpath.rb
Split out from #261, and improved
> ♻️ Reuse XPath::match

- lib/rexml/attribute.rb
- lib/rexml/document.rb
- lib/rexml/element.rb
- lib/rexml/functions.rb
- lib/rexml/namespace.rb
- lib/rexml/node.rb
- lib/rexml/parsers/baseparser.rb
- lib/rexml/parsers/xpathparser.rb
- lib/rexml/quickpath.rb
- lib/rexml/security.rb
- lib/rexml/text.rb
- lib/rexml/validation/relaxng.rb
- lib/rexml/validation/validation.rb
- lib/rexml/xpath_parser.rb
Split from #261; expanded and improved.
> ♻️ Remove redundant return statements

- lib/rexml/child.rb
- lib/rexml/text.rb
- lib/rexml/xpath.rb
- test/test_text.rb
- Fixes #273 
- "Fix" in the sense that it restores the original behavior pre-v3.2.6, regardless of its fitness for purpose.
Replaces #274
> Fix & Deprecate REXML::Text#text_indent

- Gemfile
<sub>
Please help me support open source by [sponsoring me](https://github.com/sponsors/pboling) - @pboling
</sub>
> ➖ remove ostruct from dev deps

- test/test_order.rb
JRuby's `Zlib::GzipReader#readline` does not support arguments, so when using `Zlib::GzipReader.open`, it always returns an empty string and does not function. We will temporarily exclude `Zlib::GzipReader` from test coverage.
```
$ test/run.rb --location test/test_order.rb:49
Failure: test_more_ordering(REXMLTests::OrderTester)
/Users/naitoh/ghq/github.com/naitoh/rexml/test/test_order.rb:110:in `test_more_ordering'
107:          count += 1
108:        }
109:
=> 110:        assert_equal( actual.size, count )
111:      end if defined?(Zlib::GzipReader)
112:   end
113: end
<46> expected but was
<0>
```
See: https://github.com/jruby/jruby/issues/8997
> The Zlib::GzipReader in JRuby does not behave as expected with REXML, so the test is skipped

- lib/rexml/parsers/baseparser.rb
- test/parse/test_attribute_list_declaration.rb
- test/parse/test_comment.rb
- test/parse/test_element.rb
- test/parse/test_entity_declaration.rb
- test/parse/test_processing_instruction.rb
- test/test_contrib.rb
- test/test_core.rb
- test/test_document.rb
- test/test_entity.rb
GitHub: fix https://github.com/ruby/rexml/issues/289
We must reject all well-formed XMLs:
https://www.w3.org/TR/2006/REC-xml11-20060816/#proc-types
> Validating and non-validating processors alike MUST report violations of this specification's well-formedness constraints in the content of the [document entity](https://www.w3.org/TR/2006/REC-xml11-20060816/#dt-docent) and any other [parsed entities](https://www.w3.org/TR/2006/REC-xml11-20060816/#dt-parsedent) that they read.
No root element XML is not well-formed because `document` requires one `element`:
https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-well-formed
> [1]   	document	   ::=   	( [prolog](https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-prolog) [element](https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-element) …
> Reject no root element XML as an invalid XML

- lib/rexml/parsers/baseparser.rb
- test/parse/test_document_type_declaration.rb
- test/parse/test_notation_declaration.rb
Improve maintainability by optimizing the process so that the parsing process proceeds using StringScanner.
> Use more StringScanner based API for parse_id

- lib/rexml/parsers/sax2parser.rb
- test/test_sax.rb
```
> require 'rexml/parsers/sax2parser'
> REXML::Parsers::SAX2Parser.new("<a><b></b></a>").parse
lib/rexml/parsers/sax2parser.rb:263:in 'REXML::Parsers::SAX2Parser#get_namespace': undefined method '[]' for nil (NoMethodError)
current_namespace[prefix] || current_namespace[nil]
^^^^^^^^
from lib/rexml/parsers/sax2parser.rb:150:in 'REXML::Parsers::SAX2Parser#parse'
```
> Fixed an issue when executing `REXML::Parsers::SAX2Parser#parse` without specifying `#listen`

- lib/rexml/parsers/sax2parser.rb
```
$ benchmark-driver benchmark/sax.yaml
sax     2.309k      2.317k        2.760k       2.879k i/s -     100.000 times in 0.043300s 0.043155s 0.036238s 0.034738s
Comparison:
sax
after(YJIT):      2878.7 i/s
before(YJIT):      2759.5 i/s - 1.04x  slower
after:      2317.2 i/s - 1.24x  slower
before:      2309.5 i/s - 1.25x  slower
```
- YJIT=ON : 1.04x faster
- YJIT=OFF : 1.00x faster
> Optimization of REXML::Parsers::SAX2Parser#get_procs, #get_listeners

- benchmark/parse_comment.yaml
A fix was missed in https://github.com/ruby/rexml/pull/291.
> Fix invalid XML without root element in Benchmark
